name: Build FoxRAT Combo

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2019
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1

    - name: Create VS Solution Project
      run: |
        mkdir build
        cd build
        cmake -G "Visual Studio 16 2019" -A x64 ..

    - name: Build Release
      run: msbuild build/FoxRAT.sln /p:Configuration=Release /p:Platform=x64

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: FoxRAT_Built
        path: build/Release/FoxRAT.exe
